import Image from 'next/image';
import { CiGlobe } from 'react-icons/ci';
import { IoShareOutline } from 'react-icons/io5';
import { IoIosMore } from 'react-icons/io';
import {
  FaTelegramPlane, FaYandex, FaArrowUp, FaArrowDown, FaHeart,
} from 'react-icons/fa';

import { PiStarFourFill } from 'react-icons/pi';

import { SlSocialVkontakte } from 'react-icons/sl';

import Cart from '../../components/cart/cart';

import style from './profile.module.css';

export const metadata = {
  title: 'Профиль',
  description: 'Generated by create next app',
};
const user = [
  {
    firsName: 'Anastasia',
    lastName: 'Kotlova',
    speciality: 'Designer, Illustrator 3D',
    aboutUser: 'Привет! Меня зовут Анастасия, я дизайнер и иллюстратор.Я обожаю создавать красивые и уникальные иллюстрации, которые могут передать эмоции и вдохновить людей.',
    webSite: 'https://www.flaticon.com',
    telegram: '',
    vk: '',
    dzen: '',
    dateReg: 'Member since sep 11, 2023',
  },
];
const data = [
  {
    nameTrack: 'Ветреные покатушки',
    userName: 'Воронов Велор Валерьевич',
  },
  {
    nameTrack: 'По следам приключений',
    userName: 'Муравьёв Даниил Геннадиевич',
  },
  {
    nameTrack: 'Велосипедные экскурсии',
    userName: 'Бирюков Казимир Лукьянович',
  },
  {
    nameTrack: 'По дорогам природы',
    userName: 'Поляков Виссарион Онисимович',
  },
  {
    nameTrack: 'Колесные приключения',
    userName: 'Селиверстов Феликс Улебович',
  },
  {
    nameTrack: 'Велотуры в природу',
    userName: 'Самсонов Илья Макарович',
  },
  {
    nameTrack: 'Под небом и ветром',
    userName: 'Зиновьев Трофим Владимирович',
  },
  {
    nameTrack: 'Педали вдоль троп',
    userName: 'Лапин Тихон Васильевич',
  },
  {
    nameTrack: 'Велосезоны',
    userName: 'Сазонов Семен Максимович',
  },
  {
    nameTrack: 'Ветреные покатушки',
    userName: 'Воронов Велор Валерьевич',
  },
  {
    nameTrack: 'По следам приключений',
    userName: 'Муравьёв Даниил Геннадиевич',
  },

];

export default function Profile() {
  return (
    <div className={style.container}>
      <div className={style.profile_top}>
        <Image
          className={style.poster_img}
          src="/images/poster_profile.jpg"
          alt="no-image"
          width={3125}
          height={350}
          quality={100}
          priority
          style={{ objectFit: 'cover' }}
        />
      </div>
      <div className={style.container_profile}>
        {user.map((el) => (
          <div className={style.data_profile}>
            <div className={style.profile_avatar}>
              <Image
                className={style.avatar_img}
                src="/images/avatar.jpg"
                alt="no-image"
                width={250}
                height={250}
                quality={75}
                priority
                style={{ objectFit: 'cover' }}
              />
            </div>
            <div className={style.profile_user_data}>
              <h2>{el.firsName} {el.lastName}</h2>
              <p>{el.speciality}</p>
            </div>
            <div className={style.profile_user_about}>
              {el.aboutUser}
            </div>
            <div className={style.profile_user_site}>
              <CiGlobe /> {el.webSite}
            </div>
            <div className={style.profile_user_button}>
              <div className={style.user_btn_block}>
                <button type="button">Изменить</button>
              </div>
              <div className={style.user_btn_block}>
                <button type="button">
                  <IoShareOutline />
                </button>
              </div>
              <div className={style.user_btn_block}>
                <button type="button">
                  <IoIosMore />
                </button>
              </div>
            </div>
            <div className={style.profile_user_link_socials}>
              <div className={style.profile_user_link_btn}>
                <FaTelegramPlane />
              </div>
              <div className={style.profile_user_link_btn}>
                <SlSocialVkontakte />
              </div>
              <div className={style.profile_user_link_btn}>
                <FaYandex />
              </div>
            </div>
            <div className={style.profile_user_date_reg}>
              <div className={style.borderline} />
              <div className={style.date_reg}>
                {el.dateReg}
              </div>
            </div>
          </div>
        ))}
        <div className={style.data_profile_track}>
          <div className={style.user_cart_container}>
            <div className={style.filter_block}>
              <div className={style.filter_btn}>
                <p>Новые</p> <PiStarFourFill />
              </div>
              <div className={style.filter_btn}>
                <p>Лайки</p> <FaHeart />
              </div>
              <div className={style.filter_btn}>
                <p>Дата</p> <FaArrowUp />
              </div>
              <div className={style.filter_btn}>
                <p>Дата</p> <FaArrowDown />
              </div>
            </div>
            <div className={style.cart_block}>
              {data.map((el) => (
                <div className={style.cart_container}>
                  <Cart name={el.nameTrack} userName={el.userName} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
