import Image from 'next/image';
import style from './home.module.css';
import Cart from '../../components/cart/cart';

export const metadata = {
  title: 'Главная',
  description: 'Generated by create next app',
};
const data = [
  {
    nameTrack: 'Ветреные покатушки',
    userName: 'Воронов Велор Валерьевич',
  },
  {
    nameTrack: 'По следам приключений',
    userName: 'Муравьёв Даниил Геннадиевич',
  },
  {
    nameTrack: 'Велосипедные экскурсии',
    userName: 'Бирюков Казимир Лукьянович',
  },
  {
    nameTrack: 'По дорогам природы',
    userName: 'Поляков Виссарион Онисимович',
  },
  {
    nameTrack: 'Колесные приключения',
    userName: 'Селиверстов Феликс Улебович',
  },
  {
    nameTrack: 'Велотуры в природу',
    userName: 'Самсонов Илья Макарович',
  },
  {
    nameTrack: 'Под небом и ветром',
    userName: 'Зиновьев Трофим Владимирович',
  },
  {
    nameTrack: 'Педали вдоль троп',
    userName: 'Лапин Тихон Васильевич',
  },
  {
    nameTrack: 'Велосезоны',
    userName: 'Сазонов Семен Максимович',
  },
  {
    nameTrack: 'Ветреные покатушки',
    userName: 'Воронов Велор Валерьевич',
  },
  {
    nameTrack: 'По следам приключений',
    userName: 'Муравьёв Даниил Геннадиевич',
  },
  {
    nameTrack: 'Велосипедные экскурсии',
    userName: 'Бирюков Казимир Лукьянович',
  },
  {
    nameTrack: 'По дорогам природы',
    userName: 'Поляков Виссарион Онисимович',
  },
  {
    nameTrack: 'Колесные приключения',
    userName: 'Селиверстов Феликс Улебович',
  },
  {
    nameTrack: 'Велотуры в природу',
    userName: 'Самсонов Илья Макарович',
  },
  {
    nameTrack: 'Под небом и ветром',
    userName: 'Зиновьев Трофим Владимирович',
  },
  {
    nameTrack: 'Педали вдоль троп',
    userName: 'Лапин Тихон Васильевич',
  },
  {
    nameTrack: 'Велосезоны',
    userName: 'Сазонов Семен Максимович',
  },
  {
    nameTrack: 'Ветреные покатушки',
    userName: 'Воронов Велор Валерьевич',
  },
  {
    nameTrack: 'По следам приключений',
    userName: 'Муравьёв Даниил Геннадиевич',
  },
  {
    nameTrack: 'Велосипедные экскурсии',
    userName: 'Бирюков Казимир Лукьянович',
  },
  {
    nameTrack: 'По дорогам природы',
    userName: 'Поляков Виссарион Онисимович',
  },
  {
    nameTrack: 'Колесные приключения',
    userName: 'Селиверстов Феликс Улебович',
  },
  {
    nameTrack: 'Велотуры в природу',
    userName: 'Самсонов Илья Макарович',
  },
  {
    nameTrack: 'Под небом и ветром',
    userName: 'Зиновьев Трофим Владимирович',
  },
  {
    nameTrack: 'Педали вдоль троп',
    userName: 'Лапин Тихон Васильевич',
  },
  {
    nameTrack: 'Велосезоны',
    userName: 'Сазонов Семен Максимович',
  },
  {
    nameTrack: 'Ветреные покатушки',
    userName: 'Воронов Велор Валерьевич',
  },
  {
    nameTrack: 'По следам приключений',
    userName: 'Муравьёв Даниил Геннадиевич',
  },
  {
    nameTrack: 'Велосипедные экскурсии',
    userName: 'Бирюков Казимир Лукьянович',
  },
  {
    nameTrack: 'По дорогам природы',
    userName: 'Поляков Виссарион Онисимович',
  },
  {
    nameTrack: 'Колесные приключения',
    userName: 'Селиверстов Феликс Улебович',
  },
  {
    nameTrack: 'Велотуры в природу',
    userName: 'Самсонов Илья Макарович',
  },
  {
    nameTrack: 'Под небом и ветром',
    userName: 'Зиновьев Трофим Владимирович',
  },
  {
    nameTrack: 'Педали вдоль троп',
    userName: 'Лапин Тихон Васильевич',
  },

];

export default function Home() {
  return (
    <div className={style.home_container}>
      <div className={style.banner_container}>
        <div className={style.banner}>
          <Image
            className={style.baner_img}
            src="/images/baner.jpg"
            alt="no-image"
            width={2000}
            height={200}
            quality={75}
            priority
            style={{ objectFit: 'cover' }}
          />
        </div>
      </div>
      <div className={style.cart_container}>
        <div className={style.cart_container_block}>
          {data.map((el) => (
            <Cart name={el.nameTrack} userName={el.userName} />
          ))}
        </div>
      </div>
    </div>
  );
}
